Jbpm 10187
kiegroup/drools-archive pull request #11
Opened 2023-10-26 15:07 UTC by fjtirado

**Thank you for submitting this pull request**

**NOTE!:** Double check the target branch for this PR.
The default is `main` so it will target Drools 8 / Kogito.
If this PR is not strictly related to drools and kogito project in `drools.git`, it should probably target `7.x`as a branch

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

[link](https://www.example.com)

**JIRA**: _(please edit the JIRA link if it exists)_

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-10-26 15:12 UTC, mareknovotny commented
jenkins do fdb

2023-10-26 15:15 UTC, mareknovotny commented
jenkins do fdb

2023-10-26 16:10 UTC, gmunozfe commented on drools-persistence/drools-persistence-api/src/main/java/org/drools/persistence/api/TransactionManagerHelper.java
> +            });
Could we simplify the custom Comparator with this?
```suggestion
            SortedSet<Transformable> sorted = new TreeSet<>(Comparator.comparing(o -> o.getClass().getSimpleName()));
```

2023-10-26 16:10 UTC, gmunozfe commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/PersistableRunner.java
> +            this.sessionInfo = sessionInfo;
Is this sessionInfo used? If not, you can remove all changes related to it.

2023-10-27 13:56 UTC, fjtirado commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/PersistableRunner.java
> +            this.sessionInfo = sessionInfo;
yes it is used in this class to avoid a null pointer

2023-10-27 14:59 UTC, gmunozfe requested changes
@fjtirado Sorry, I didn't include the import in my comment and compilation fails:
16:03:42  [ERROR] /home/jenkins/workspace/KIE/7.x/pullrequest/drools-7.x.pr/bc/kiegroup_drools/drools-persistence/drools-persistence-api/src/main/java/org/drools/persistence/api/TransactionManagerHelper.java:[64,61] cannot find symbol
16:03:42    symbol:   variable Comparator
16:03:42    location: class org.drools.persistence.api.TransactionManagerHelper

2023-10-31 10:56 UTC, mareknovotny commented
so can you suggest proper import then? @gmunozfe

2023-11-02 10:02 UTC, fjtirado commented
> so can you suggest proper import then? @gmunozfe

@mareknovotny @gmunozfe 

Im trying to fix the issue, but Im getting this when forcing the push
```

Repository https://github.com/kiegroup/drools.git

pre-receive hook declined
```

2023-11-02 10:31 UTC, mareknovotny commented
hmm, what is your push command? @fjtirado 
I would expect as you pushed this branch before it should work for you, but i will check if by any chance this branch is not by protected pattern guarded

2023-11-02 12:14 UTC, fjtirado commented
> hmm, what is your push command? @fjtirado I would expect as you pushed this branch before it should work for you, but i will check if by any chance this branch is not by protected pattern guarded
> 
> UPDATE: no, this branch is not guarded by protected branch pattern

I edited directly in the PR, I was messing up with branches from my IDE, sorry about that

2023-11-02 14:56 UTC, mareknovotny commented
jenkins retest this please

2023-11-02 14:59 UTC, mareknovotny commented
there is some weird sonarcloud analysis error not related to this change, i am not able to reproduce it locally yet. My local build fails on h2 persistence module due `Caused by: org.h2.jdbc.JdbcSQLException: Feature not supported: "-ifNotExists" [50100-197]`
but there were removed org.drools:drools project in Sonarcloud due Apache migration of repository, but now it should be recreated for 7.x branch. But this is not clear as not fixed. I am trying to sort this as it affect all Drools PR here in this repository

2023-11-03 10:32 UTC, mareknovotny commented
jenkins retest this please

i recreated org.drools:drools project on sonarcloud.io so we will see if that is enough to pass it

2023-11-06 16:23 UTC, merged